version: "3.9"

services:
  web:
    container_name: web
    build: .
    restart: always
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo/notesdb
      - PORT=4000
      - NODE_ENV=development
    command: npm start

  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
